from PyQt6.QtGui import QAction


def build_main_window_menu(main_window):
    menubar = main_window.menuBar()
    menubar.setNativeMenuBar(False)

    file_menu = menubar.addMenu("&File")
    file_menu.addAction(main_window.open_file_action)
    file_menu.addAction(main_window.save_action)
    file_menu.addAction(main_window.save_as_action)
    file_menu.addSeparator()
    file_menu.addAction(main_window.close_tab_action)
    file_menu.addAction(main_window.close_all_tabs_action)
    file_menu.addSeparator()
    file_menu.addAction(main_window.exit_action)

    object_menu = menubar.addMenu("&Object")
    create_menu = object_menu.addMenu("Create")
    create_menu.addAction(main_window.create_table_action)
    create_menu.addAction(main_window.create_view_action)
    object_menu.addAction(main_window.query_tool_obj_action)
    object_menu.addAction(main_window.refresh_action)
    object_menu.addAction(main_window.delete_object_action)

    edit_menu = menubar.addMenu("&Edit")
    edit_menu.addAction(main_window.undo_action)
    edit_menu.addAction(main_window.redo_action)
    edit_menu.addSeparator()
    edit_menu.addAction(main_window.cut_action)
    edit_menu.addAction(main_window.copy_action)
    edit_menu.addAction(main_window.paste_action)
    edit_menu.addAction(main_window.select_all_action)
    edit_menu.addAction(main_window.clear_all_action)
    edit_menu.addSeparator()
    edit_menu.addAction(main_window.format_sql_action)
    edit_menu.addAction(main_window.goto_line_action)
    edit_menu.addAction(main_window.comment_block_action)
    edit_menu.addAction(main_window.uncomment_block_action)
    edit_menu.addSeparator()
    edit_menu.addAction(main_window.upper_case_action)
    edit_menu.addAction(main_window.lower_case_action)
    edit_menu.addAction(main_window.initial_caps_action)
    edit_menu.addSeparator()

    actions_menu = menubar.addMenu("&Actions")
    actions_menu.addAction(main_window.execute_action)
    actions_menu.addAction(main_window.execute_new_tab_action)
    actions_menu.addAction(main_window.explain_action)
    actions_menu.addAction(main_window.cancel_action)

    tools_menu = menubar.addMenu("&Tools")
    tools_menu.addAction(main_window.query_tool_action)
    tools_menu.addAction(main_window.refresh_action)
    tools_menu.addAction(main_window.restore_action)

    window_menu = menubar.addMenu("&Window")
    window_menu.addAction(main_window.minimize_action)
    window_menu.addAction(main_window.zoom_action)
    window_menu.addSeparator()
    close_action = QAction("Close", main_window)
    close_action.triggered.connect(main_window.close)
    window_menu.addAction(close_action)

    help_menu = menubar.addMenu("&Help")
    help_menu.addAction(main_window.sqlite_help_action)
    help_menu.addAction(main_window.postgres_help_action)
    help_menu.addAction(main_window.oracle_help_action)
    help_menu.addSeparator()
    help_menu.addAction(main_window.about_action)
